{
 "title": "fluent-bit",
 "description": "Fluent Bit dashboard.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\",namespace=\"$namespace\",created_by_kind=\"DaemonSet\",created_by_name=\"$release\"},pod)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": "${VAR_NAMESPACE}" },
   { "name": "release", "label": "Release", "query": "${VAR_RELEASE}" },
   { "name": "fullname", "label": "Full Name", "query": "${VAR_FULLNAME}" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{job=\"kube-state-metrics\",namespace=\"$namespace\",created_by_kind=\"DaemonSet\",created_by_name=\"$release\"})",
     "legendFormat": "Active Pods"
    },
    {
     "expr": "sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"Ready\",status=\"true\"})",
     "legendFormat": "Ready Nodes"
    },
    {
     "expr": "sum(kube_node_status_condition{job=\"kube-state-metrics\",condition!=\"Ready\",status=\"true\"})",
     "legendFormat": "Non-Ready Nodes"
    }
   ]
  },
  { "title": "Fluent Bit Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Input Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Input Records Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Record Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Retry/Failed Rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}} Retries to {{name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}} Failed Retries to {{ name }}"
    }
   ]
  },
  {
   "title": "Output Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "errors/sec" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Filter Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_bytes_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Filter Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_records_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Filter Add Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_add_records_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  {
   "title": "Filter Drop Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_drop_records_total{job=\"$release\",namespace=\"$namespace\"}[5m])) by (pod, name)",
     "legendFormat": "{{pod}}/{{name}}"
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\",namespace=\"$namespace\",pod=~\"$pod\",container=\"fluent-bit\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{job=\"kube-state-metrics\",namespace=\"$namespace\",pod=~\"$pod\", container=\"fluent-bit\",resource=\"memory\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",pod=~\"$pod\",container=\"fluent-bit\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{job=\"kube-state-metrics\",namespace=\"$namespace\",pod=~\"$pod\",container=\"fluent-bit\",resource=\"cpu\"})",
     "legendFormat": "{{ pod }} request"
    }
   ]
  }
 ]
}